// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPAI_IVR;

#nullable disable

namespace PPAI_IVR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230526025959_baseCompleta")]
    partial class baseCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PPAI_IVR.Clases.CambioEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LlamadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("LlamadaId");

                    b.ToTable("CambioEstado");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroCelular")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.InformacionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ValidacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datoAValidar")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ValidacionId");

                    b.ToTable("InformacionCliente");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Llamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionOperador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleAccionRequerida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duracion")
                        .HasColumnType("float");

                    b.Property<bool>("EncuestaEnviada")
                        .HasColumnType("bit");

                    b.Property<string>("ObservacionAuditor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpcionLlamadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OpcionLlamadaId");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.OpcionLlamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroOrden")
                        .HasColumnType("int");

                    b.Property<string>("audioMensajeSubOpciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mensajeSubOpcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpcionLlamada");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.SubOpcionLlamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OpcionLlamadaId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroOrden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpcionLlamadaId");

                    b.ToTable("SubOpcionLlamada");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Validacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpcionLlamadaId")
                        .HasColumnType("int");

                    b.Property<string>("audioMensajeValidacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OpcionLlamadaId");

                    b.ToTable("Validacion");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.CambioEstado", b =>
                {
                    b.HasOne("PPAI_IVR.Clases.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("PPAI_IVR.Clases.Llamada", null)
                        .WithMany("CambiosDeEstados")
                        .HasForeignKey("LlamadaId");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.InformacionCliente", b =>
                {
                    b.HasOne("PPAI_IVR.Clases.Cliente", null)
                        .WithMany("InformacionCliente")
                        .HasForeignKey("ClienteId");

                    b.HasOne("PPAI_IVR.Clases.Validacion", "Validacion")
                        .WithMany()
                        .HasForeignKey("ValidacionId");

                    b.Navigation("Validacion");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Llamada", b =>
                {
                    b.HasOne("PPAI_IVR.Clases.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("PPAI_IVR.Clases.OpcionLlamada", "OpcionLlamada")
                        .WithMany()
                        .HasForeignKey("OpcionLlamadaId");

                    b.Navigation("Cliente");

                    b.Navigation("OpcionLlamada");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.SubOpcionLlamada", b =>
                {
                    b.HasOne("PPAI_IVR.Clases.OpcionLlamada", null)
                        .WithMany("subOpcionLlamadas")
                        .HasForeignKey("OpcionLlamadaId");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Validacion", b =>
                {
                    b.HasOne("PPAI_IVR.Clases.OpcionLlamada", null)
                        .WithMany("validacionesRequeridas")
                        .HasForeignKey("OpcionLlamadaId");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Cliente", b =>
                {
                    b.Navigation("InformacionCliente");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.Llamada", b =>
                {
                    b.Navigation("CambiosDeEstados");
                });

            modelBuilder.Entity("PPAI_IVR.Clases.OpcionLlamada", b =>
                {
                    b.Navigation("subOpcionLlamadas");

                    b.Navigation("validacionesRequeridas");
                });
#pragma warning restore 612, 618
        }
    }
}
